### ISSUE TITLE
Any possibility to have multiple WebView controls per application?

### ISSUE THREAD

**Issue by anatoletartakovsky** [tuarua/WebViewANE#105]
- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 0.0.27

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    
- **If Windows is it?**
    - 32bit or 64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

- **Which version of AIR are you using?**
    - 19,20.. etc?

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
You don't even mention what OS you are talking about

**Comment by anatoletartakovsky** [comment]
I am very sorry. Windows/CEF. The question is about a sample that would allow to open multiple WebView instances in multi-window air application. In particular, I am referencing 
"The Cef view and processes can only be attached once to your app. Therefore only one instance can be created and used."
If I just clone the window sample code, I get error:
[CommonDependencies] Initalizing ANE... [WebViewANE] Initalizing ANE... [WebViewANE] Initalizing ANE... 2017-11-22 23:36:17.601 adl[76540:2055824] * Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to add script message handler with name 'webViewANE' when one already exists.'
Better question would be if there could be a sample of global static object and binding would be limited to individual tabs. 
Thak you
Anatole Tartakovsky

**Comment by tuarua** [comment]
You can only init single ANE due to Chromium Embedded Framework limitation.
The Desktop ANE supports multiple webviews in the form of "tabs" - like a browser tab.
Browser popups are supported.
However, multiple AIR windows are not supported. 
The webview control is a separate Child Window + Process attached to the AIR window.
To handle attaching + tracking spinoffs of this Child window to possibly multiple AIR child windows is an extremely large task and is just not on the roadmap.

**Comment by coxfrederic** [comment]
Is it possible to be able to choose the window? For example to never attach to the main AIR window but always to a new popup window? Or is that also an extremely large task?

For an app I display a HTML preview in a popup window so that would be a solution. Currently the popup window opens but the HTML content replaces my main app stage contents

**Comment by tuarua** [comment]
What you describe is the same as above and involves same level of complexity and size of task.

If you want popup type.
- create a small webview with empty page and set as invisible
- call JS on this page which opens your popup using any of the JS methods supplied.
