### ISSUE TITLE
is it able to run in Animate CC?

### ISSUE THREAD

**Issue by kwanggaeto** [tuarua/WebViewANE#14]
hi,

you did work so interesting ANE :)

i know it is work fine in Flash Builder 4.7.

but, I'm fail to run in Animate CC.

is it able to run in Animate CC?

**Comment by tuarua** [comment]
I ran a quick test. It works in Animate CC only when I build release. Debug doesn't work. I don't know why.

**Comment by tuarua** [comment]
I don't own a copy of Animate to be able to test further. If someone has an example .fla which runs in both Debug and release please provide

**Comment by berkeley-games** [comment]
I have successfully run a debug build and packaged a release build through both Adobe Animate CC and IntelliJ IDEA.

1. Open the Publish Settings dialog

2. Open ActionScript settings dialog

3. Under "Library Path" tab, add WebViewANE.ane file with the "Browse to a Native Extension" button

![ActionScript 3 Settings](http://i.imgur.com/qZBYrE3.png)

5. Close ActionScript settings dialog

6. Open AIR settings dialog

7. (Optional) Add every WebViewANE dependency to the "Included Files" list. This allows you to send a single installer generated from Animate CC with all of the dependencies included. (but it's annoying to do because you have to browse for each file individually)

![AIR Settings](http://i.imgur.com/d2T8nyv.png)

8. Publish!

**Comment by tuarua** [comment]
Many thanks for supplying the screenshots
