### ISSUE TITLE
Windows VC++ Redistributable

### ISSUE THREAD

**Issue by rodrigogermanlopez** [tuarua/WebViewANE#25]
**NOT AN ISSUE, BUT A REQUEST.**

By any chance... can u zip the files mentioned on the Chromium documentation?

> # For VC++ 2013 (x86)
> C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x86\Microsoft.VC120.CRT
> # For VC++ 2013 (x64)
> C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x64\Microsoft.VC120.CRT

I just don't have elevated access to install the VC runtime on one setup, and can't find the way to make the ANE work otherwise... and I didn't find those folders.

Thanks.

**Comment by tuarua** [comment]
I don't have Visual Studio 2013. I have 2015.
You'll need to install Visual Studio on your own machine and then grab the files out of that folder. You can't find the folders because you don't have Visual Studio 2013 installed.
https://www.visualstudio.com/en-us/news/releasenotes/vs2013-community-vs.

Normally you don't include such dlls (or .NET etc). You create an installer using Wix or Innosetup and mark these as pre-requisites. It handles this. It's unusual to expect to create a Windows desktop app where you can't run an install process of some kind.
