### ISSUE TITLE
loading same local mp4 twice edge

### ISSUE THREAD

**Issue by jasonJamEther** [tuarua/WebViewANE#256]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue. Yes
    
- **What version of the product are you using?**
    - What version are you using?
settings2.engine

- **On what operating system?**
    Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    64bit

- **Which IDE are you using?**
    Animate

- **Which version of AIR are you using?**
    32.0.0.89

I have a simple app on windows that is using the Edge webview so that I can load LOCAL html files with mp4 videos. The first time I open and play the video everything works great. But if I re-open the link with the same video it won't play. It behaves as if mp4s are not supported. If I go to any of my other links which I haven't viewed they work for the first time but only the first time. This only happens with local html content. External pages work no matter how many times I reload the page with the video. 

Here is a sample of the local html I am trying to load. Really nothing more that a video tag with the local video source:
https://phoenixinfuse.s3.amazonaws.com/webview_video_html.zip

If I restart the app everything works again (once). I have tried clearing cache and disabling cache but this has no effect. Based on the AS documentation cache can't be cleared on windows anyway. Would love a work around for this if possible.

**Comment by tuarua** [comment]
I have looked into this.
It looks like a strange bug in the MS WebView itself.

If I load the mp4 from JS, ie not even loading the page, it  loads the first time, but returns an invalid source error the second time

```
const vid = document.getElementById('vid');
vid.src = 'small.mp4';
```

If I try the same with an img tag it has no problem.

MS have now marked WebView as deprecated so they are unlikely to fix it.

You can either run your html pages from a local webserver (this is recommended rather than trying to use loadLocal) or you can contact me if you are interested in a version of the Chromium Engine with mp4 support.
