### ISSUE TITLE
Ability to externalise dependancies

### ISSUE THREAD

**Issue by TomByrne** [tuarua/WebViewANE#56]
This extension works well, unfortunately it adds considerable size to the application (when doing a windows build).

I have tried moving the DLLs to other locations and attempted various ways of giving the main application access to them, but I haven't had any luck yet.

Is there a way to use the DLL files from a different location, so that we can deploy the dependencies separately to the main application?

Is this even possible with the way that AIR extensions use DLLs?

**Comment by tuarua** [comment]
The added size is because the webview is essentially a whole web browser based on Chrome on Windows.
Should Microsoft ever add a shared control based on Edge then I would move to that (it's IE9 atm!!)
I use the inbuilt browser on OSX and it is a lot easier to maintain.

Moving dlls around is not as simple as it sounds. it's not AIR specific.

Please see this Microsoft which explains things
[Search Path Used by Windows to Locate a DLL](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx)

While it may be possible to dynamically load dlls at runtime through a bit of hackery, many of the dlls used are not under my control. They have their own linking defined.

I've had push-back from people thinking it's outrageous that they have to copy some dlls and package their apps.
It's just part and parcel of developing Windows apps.
And a small price to pay for the fact that you are actually able to run and control Chrome from inside AIR.

**Comment by born2net** [comment]
I just wanted to say thank you for the amazing support on this open-source product!!!!!!!!!!!!

**Comment by tuarua** [comment]
@born2net No problem

**Comment by TomByrne** [comment]
I have messed around with the files and found that I can externalise most of them without issue.

Currently these are the files I'm including in my app:
CefSharp.BrowserSubprocess.Core.dll
CefSharp.BrowserSubprocess.exe
CefSharp.Core.dll
CefSharp.dll
CefSharp.WinForms.dll
CefSharpLib.dll
FreSharp.dll
FreSharpCore.dll
libEGL.dll
Newtonsoft.Json.dll

These files alone only add about 1mb to my app, the rest of the files must be on the system PATH though. I'm confident more of the files could be externalise with more tinkering (e.g. Newtonsoft.Json.dll) but for now this suits my purposes.

I'm not entirely sure when each file is used, so it's not unlikely I've removed something which shouldn't be removed. I'll keep an eye on this and post here if I need to move some files back into the main app.
