### ISSUE TITLE
Can not run on IOS

### ISSUE THREAD

**Issue by nidiy** [tuarua/WebViewANE#58]
Hello, I use the "WebView ANE-mobile.ane" release IOS version can not run, open the APP on the exit. But in the normal operation of Android, what is the reason?

**Comment by tuarua** [comment]
please see the iOS section of the README
https://github.com/tuarua/WebViewANE#ios
https://github.com/tuarua/WebViewANE#running-on-device-

**Comment by nidiy** [comment]
@tuarua  Ok, thank you, i try it

**Comment by tuarua** [comment]
Were you able to run on your device ?

**Comment by nidiy** [comment]
hello,
@tuarua   Has not resolved, I think my packaging is no problem, whether the need to re-release ANE?

**Comment by tuarua** [comment]
The ANE is fine.
I have produced a youtube video which walks through how to package the example iOS app so that it runs on device (iPad in my case)
Please follow carefully.
https://www.youtube.com/watch?v=H-G8WugNFQM&feature=youtu.be

As I say in the notes this ANE uses Swift and so the release app must be packaged with the Frameworks and resigned.
The tool helps with this.

**Comment by tuarua** [comment]
Can I close this ticket ?

**Comment by nidiy** [comment]
OK
