### ISSUE TITLE
Is it possible to develop for Windows and use a Mac for this?

### ISSUE THREAD

**Issue by xergon** [tuarua/WebViewANE#59]
Hello,
we want to target Windows and OSX with our App.
Do we need Windows to publish a Windows air runtime with your ANE?  Or can we continue working with OSX?

**Comment by tuarua** [comment]
You can develop your app on either platform but see this info from the Adobe documentation.

From the **Adobe docs**
_You cannot create a cross-platform AIR package (a .air package) for an application that uses a native extension, because native extensions usually contain native code._

So you must create an exe and a .app/.dmg when using **any** ANE

From the **Adobe docs**
_You must use ADT on the same operating system as that of the native installer file you want to generate. So, to create an EXE file for Windows, run ADT on Windows. To create a DMG file for Mac OS, run ADT on Mac OS._  

So you must compile your final package on the target OS. **This is not specific to this ANE. This is an AIR thing.**

If you intend to develop on OSX but also target Windows you can
1) buy a very cheap Win laptop to compile + test
2) Run a dual boot OSX and WIN using Parallels/Bootcamp on your mac. This is what many people do.

**Comment by tuarua** [comment]
Closing as I have answered the Question
