### ISSUE TITLE
CommonDependencies.ane for windows is lacking

### ISSUE THREAD

**Issue by olive009** [tuarua/WebViewANE#75]
- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 0.0.27

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    
- **If Windows is it?**
    - 32bit or 64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

- **Which version of AIR are you using?**
    - 19,20.. etc?

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
Read the README before opening an issue.
https://github.com/tuarua/WebViewANE#-version-0026

**Comment by olive009** [comment]
Hi Tuarua, I've updated the details, please check.

**Comment by tuarua** [comment]
Hi,
CommonDependencies.ane bundles Swift libraries and contains OSX and "default" implementations. It doesn't contain Windows-x86-64 because it doesn't need to. Default acts here.
Although Flash Builder displays a red X everything builds OK in debug and release modes.

![image](https://user-images.githubusercontent.com/12083217/29558203-591ea8a6-8723-11e7-9cb8-595886a25e12.png)

![image](https://user-images.githubusercontent.com/12083217/29558187-4968a9c0-8723-11e7-876d-e0caae3a23e9.png)

If you are **only** targeting Windows you can remove this ANE from your project.

**Comment by olive009** [comment]
Hi Tuarua, 
after removing the CommonDependencies.ane, the build can't be passed, due to the following line would have error:

private var commonDependenciesANE:CommonDependencies = new CommonDependencies();//must create before all others

**Comment by tuarua** [comment]
Like I said if you are only targeting Windows you can remove this ANE from the project. That naturally includes removing that line - use common sense.
